services:
  - type: web
    name: uk-company-ownership-api
    env: python
    region: oregon
    build:
      packages:
        - curl
        - build-essential
        - pkg-config
        - libssl-dev
        - rustc
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: COMPANIES_HOUSE_API_KEY
        sync: false  # Set this manually in Render dashboard
    healthCheckPath: /health
